
# La URL apunta a tu localhost en el puerto 3306 (donde está tu Docker)
# El "createDatabaseIfNotExist=true" es magia pura: si la BD no existe, Spring la crea sola.
spring.datasource.url=jdbc:mysql://localhost:3306/cartas_del_reino?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# CREDENCIALES (Revisá tu archivo .env)
# ===============================
# Acá van el usuario y contraseña de tu MySQL de Docker.
# Por lo general en la facu usan root y root, o root y test.
spring.datasource.username=root
spring.datasource.password=rootpassword

# ===============================
# CONFIGURACIÓN DE HIBERNATE (El "Motor")
# ===============================
# Le decimos explícitamente que estamos usando MySQL versión 8
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Muestra en la consola el SQL que ejecuta por detrás (muy útil para debuggear)
spring.jpa.show-sql=true

# Crea las tablas automáticamente en base a tus clases @Entity
spring.jpa.hibernate.ddl-auto=create

# Ejecuta el archivo data.sql apenas termina de crear las tablas
spring.sql.init.mode=always